name: agro_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.3.8
  styled_widget: 0.4.0+3
  dio: 4.0.0
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: BrandonText
      fonts:
        - asset: assets/fonts/BrandonTextRegular.otf
        - asset: assets/fonts/BrandonTextBold.otf
          weight: 700
  assets:
    - assets/img/logos/
    - assets/img/splash/
    - assets/img/icons/
  uses-material-design: true
